# Generated by Django 5.0.2 on 2024-03-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highestedu',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobcategory',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobdescription',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='max_salary',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='min_salary',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='shift',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
