# Generated by Django 5.0.2 on 2024-03-07 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_company_descriptionn_company_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Descriptionn',
            new_name='Description',
        ),
    ]
