# Generated by Django 5.0.2 on 2024-03-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_jobdetails_compnaywebsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='compnaywebsite',
            new_name='companywebsite',
        ),
    ]
