# Generated by Django 5.0.2 on 2024-03-09 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_compnaywebsite_jobdetails_companywebsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=250)),
                ('min_salary', models.CharField(max_length=250)),
                ('max_salary', models.CharField(max_length=250)),
                ('resume', models.FileField(upload_to='app/resume')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobdetails')),
            ],
        ),
    ]
